import type { Metadata } from "next";
import { Gothic_A1 } from "next/font/google";
import "@/styles/globals.css";

const gothicA1 = Gothic_A1({ subsets: ["latin"], weight: ["300", "400", "500", "700"] });

import { AntdProvider } from "../components/providers/antd-provider";

export const metadata: Metadata = {
  title: "UI Templates for Next 14 - BUNGRIT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={gothicA1.className}>
        <AntdProvider>{children}</AntdProvider>
      </body>
    </html>
  );
}
